apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: proxy
data:
  Caddyfile: |
    :80 {
        @nextcloud host nextcloud.chungo.dev

        handle @nextcloud {

            rewrite /.well-known/carddav /remote.php/dav/
            rewrite /.well-known/caldav /remote.php/dav/

            reverse_proxy http://192.168.15.30:9000 {
            
                header_up Host {host}
                header_up X-Forwarded-Proto {scheme}
                header_up X-Real-IP {remote_host}
                header_up X-Forwarded-For {remote}
            }
        }
        
        @hassio host hassio.chungo.dev

        handle @hassio {
            reverse_proxy http://192.168.1.8:8123 {
                header_up Host {http.request.host}
                header_up X-Forwarded-Proto "https"
                header_up X-Forwarded-Host {http.request.host}
                header_up X-Forwarded-For {http.request.remote.host}
                header_up X-Real-IP {http.request.remote.host}
            }
        }

        handle {
            respond "This domain is not configured on Caddy." 404
        }
    }