apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: proxy
data:
  Caddyfile: |
    :80 {
        @nextcloud host nextcloud.chungo.dev

        handle @nextcloud {

            rewrite /.well-known/carddav /remote.php/dav/
            rewrite /.well-known/caldav /remote.php/dav/

            reverse_proxy http://192.168.15.30:80 {
            
                header_up Host {host}
                header_up X-Forwarded-Proto {scheme}
                # header_up X-Real-IP {remote_host}
                # header_up X-Forwarded-For {remote}
                header_up X-Real-IP {http.request.header.X-Real-IP}
                header_up X-Forwarded-For {http.request.header.X-Forwarded-For}
            }

        }

        handle {
            respond "This domain is not configured on Caddy." 404
        }
    }
